config/routes.rb
Rails.application.routes.draw do
  root 'documents#index'
  resources :documents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.slim
= form_with model: @document, local: true do |f|
  - if @document.errors.any?
    #error_explanation
      h2 = "#{pluralize(@document.errors.count, "error")} prohibited this document from being saved:"
      ul
        - @document.errors.full_messages.each do |message|
          li = message
  .form-group
    = f.label :title, class: 'form-label'
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :content, class: 'form-label'
    = f.text_area :content, class: 'form-control', 'data-provider': :summernote

  .actions = f.submit class: 'btn btn-primary'

app/views/documents/edit.html.slim
h1 Editing document

== render 'form'

=> link_to 'Show', @document
'|
=< link_to 'Back', documents_path

app/views/documents/index.html.slim
h1 Listing documents

table.table.table-striped
  thead
    tr
      th title
      th
      th
      th

  tbody
    - @documents.each do |document|
      tr
        td = document.title
        td = link_to 'Show', document
        td = link_to 'Edit', edit_document_path(document)
        td = link_to 'Destroy', document, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Document', new_document_path

app/views/documents/new.html.slim
h1 New document

== render 'form'

= link_to 'Back', documents_path

app/views/documents/show.html.slim
p#notice = notice

dl
  dt title
  dd = @document.title
  dt content
  dd.text-break
    .border.rounded.p-3
      == @document.content

=> link_to 'Edit', edit_document_path(@document)
'|
=< link_to 'Back', documents_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SummernoteTest
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = yield